name: "imageclef_2013"
data {
  name: "train_data"
  file_pattern: "/home/rssteffey/Documents/imageclef_2013/train.npy"
  size: 50000
  dimensions: 2000
  stats_file: "clef_stats.npz"
}
gpu_memory: "600M"
main_memory: "2G"
